In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# Step - 2 ( Data Loading )
df=pd.read_csv(r"C:\Users\sajid\Downloads\Machine Learning\Linear Regression\revenue_prediction (1) (1).csv")
df

,Id,Name,Franchise,Category,City,No_Of_Item,Order_Placed,Revenue
0,101,HungryHowie'sPizza,Yes,Mexican,Bengaluru,55,5.5,5953753
1,102,CharleysPhillySteaks,No,Varied Menu,Gurugram,72,6.8,7223131
2,103,Chuy's,Yes,Chicken,Pune,25,1.9,2555379
3,104,O'Charley's,Yes,Italian/Pizza,Mumbai,18,2.5,2175511
4,105,PolloTropical,Yes,Pizza,Noida,48,4.2,4816715
...,...,...,...,...,...,...,...,...
95,196,Wetzel'sPretzels,No,Italian/Pizza,Bengaluru,19,1.1,1270499
96,197,LaMadeleineCountryFrenchCafe,Yes,Varied Menu,Bengaluru,75,6.3,6412623
97,198,Giordano's,Yes,Varied Menu,Gurugram,77,6.2,6694797
98,199,IslandsFineBurgers&Drinks,Yes,Sports Bar,Pune,25,2.1,2344689
99,200,Mimi'sBistro&Bakery,No,BBQ,Mumbai,50,4.4,4567678

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            100 non-null    int64
 1   Name          100 non-null    object
 2   Franchise     100 non-null    object
 3   Category      100 non-null    object
 4   City          100 non-null    object
 5   No_Of_Item    100 non-null    int64
 6   Order_Placed  100 non-null    float64
 7   Revenue       100 non-null    int64
dtypes: float64(1), int64(3), object(4)
memory usage: 6.4+ KB

In [4]:
df.isnull().sum()

Id              0
Name            0
Franchise       0
Category        0
City            0
No_Of_Item      0
Order_Placed    0
Revenue         0
dtype: int64

In [5]:
print(df.isnull().sum().sum())

0

In [6]:
print(df.duplicated().sum())

0

In [7]:
from sklearn.preprocessing import LabelEncoder
le =  LabelEncoder()

for i in df.columns:
  if df[i].dtype=="object":
    df[i]= le.fit_transform(df[i])

In [8]:
x=df.drop(columns="Revenue")
y=df["Revenue"]

In [9]:
x

     Id  Name  Franchise  Category  City  No_Of_Item  Order_Placed
0   101    40          1        12     0          55           5.5
1   102    14          0        19     1          72           6.8
2   103    16          1         5     4          25           1.9
3   104    60          1        11     2          18           2.5
4   105    68          1        13     3          48           4.2
..  ...   ...        ...       ...   ...         ...           ...
95  196    96          0        11     0          19           1.1
96  197    47          1        19     0          75           6.3
97  198    35          1        19     1          77           6.2
98  199    41          1        17     4          25           2.1
99  200    55          0         2     2          50           4.4

[100 rows x 7 columns]

In [10]:
y

0     5953753
1     7223131
2     2555379
3     2175511
4     4816715
       ...
95    1270499
96    6412623
97    6694797
98    2344689
99    4567678
Name: Revenue, Length: 100, dtype: int64

In [45]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split ( x , y , train_size=0.8 , random_state= 42)

In [12]:
x_train

     Id  Name  Franchise  Category  City  No_Of_Item  Order_Placed
55  156    54          0        14     2          79           6.8
88  189    10          1         4     2          25           1.9
26  127    26          0        18     0          28           2.1
42  143    63          1         1     0          55           4.8
69  170    23          0        16     3          39           3.3
..  ...   ...        ...       ...   ...         ...           ...
60  161     0          0        12     0          38           3.0
71  172    18          0        19     2          49           4.0
14  115    64          0        14     0          22           1.8
92  193    78          1        19     0          72           6.5
51  152     2          0        13     2          38           3.1

[80 rows x 7 columns]

In [13]:
y_train

55    6941173
88    2025297
26    2967425
42    4952255
69    3452382
       ...
60    3164972
71    4136425
14    1099097
92    6782425
51    3273041
Name: Revenue, Length: 80, dtype: int64

In [15]:
from sklearn.linear_model import LinearRegression

model_1 = LinearRegression()

In [31]:
model_1.fit(x_train , y_train)

LinearRegression()

In [17]:
y_pred = model_1.predict(x_test)

In [18]:
y_pred

array([6610484.93142059, 5613271.30152286, 3817105.02048179,
       4146922.93112893, 4365714.11206967, 3810566.02285223,
       3938440.02234058, 3467277.43064972, 4089273.94326184,
       6576390.58781053, 5487860.45771965, 3129316.87423342,
       2792329.12578932, 2255489.31071248, 3527565.71523309,
       4577682.37757051, 5082034.41146382, 1430233.21615118,
       1771334.93256402, 2211064.62548494])

In [21]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
print("R2 score of the model :" , r2_score(y_test ,y_pred )*100)
print("Avergae root error between actual charges amount and predicted charges amount is :" ,np.sqrt(mean_squared_error(y_test , y_pred)))

R2 score of the model : 86.21903965008737
Avergae root error between actual charges amount and predicted charges amount is : 449208.8929252029

#PCA

In [22]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [42]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

In [46]:
pca = PCA()
X_pca = pca.fit_transform(X_scaled)

In [47]:
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X_scaled)

In [48]:
model_2 = LinearRegression()

In [49]:
from sklearn.model_selection import train_test_split
x_train_pca , x_test_pca , y_train_pca , y_test_pca = train_test_split ( X_pca , y , train_size=0.8 , random_state= 42)

In [50]:
model_2.fit(x_train_pca , y_train_pca)

LinearRegression()

In [51]:
y_pca_pred = model_2.predict(x_test_pca)

In [53]:
y_pca_pred

array([5239001.39466968, 5182949.79673015, 3818888.52353872,
       4368824.11037334, 4310052.87527312, 3663813.19125383,
       3725580.46700517, 3262447.78034933, 3845177.63674446,
       5803406.39719664, 5082831.66704602, 3030752.40223799,
       2673134.70231042, 2368752.34006579, 3517911.01991074,
       4318447.86672834, 5206987.47091781, 1706866.62635724,
       1896196.38459051, 2368049.80620268])

In [58]:
print("R2 score of the model :" , r2_score(y_test ,y_pred )*100)

R2 score of the model : 86.21903965008737

In [60]:
print("R2 score of the model :" , r2_score(y_test ,y_pred )*100)
print("R2 score of the model after PCA is  :" , r2_score( y_test_pca , y_pca_pred )*100)

R2 score of the model : 86.21903965008737
R2 score of the model after PCA is  : 84.46886202330647